inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/BlockLength:
  Max: 29

# Offense count: 1
Metrics/AbcSize:
  Max: 33

# Offense count: 9
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 27

# Offense count: 2
# Configuration parameters: Exclude.
Naming/FileName:
  Exclude:
    - 'bin/passenger-datadog'

# Offense count: 1
# Configuration parameters: Exclude.
Style/Documentation:
  Exclude:
    - 'lib/passenger_datadog.rb'

# This is needed for Ruby 1.8.7 compatibility
Style/HashSyntax:
  EnforcedStyle: hash_rockets
