language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - ruby-head
  - jruby-19mode
  - jruby-9.0.1.0
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
    - rvm: jruby-9.0.1.0
  fast_finish: true
script:
  - bundle exec rake
